export const carouselImgNameAry = [
  "notion-js-menu.jpg",
  "notion-js-hosting.jpg",
  "notion-js-class.jpg",
  "notion-js-object.jpg",
  "react-1.jpg",
  "react-2.jpg",
  "react-3.jpg",
  "redux-1.jpg",
  "redux-2.jpg",
  "redux-3.jpg",
  "xmind-css-1.png",
  "xmind-css-2.png",
  "xmind-css-flex.png",
  "xmind-css-selector.png",
  "xmind-bs5.png",
  "xmind-js-dom.png",
];
